# Generated by Django 5.2.6 on 2025-09-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('area_post_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('area_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('service_merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.merchant')),
            ],
        ),
    ]
