# Generated by Django 5.2.6 on 2025-09-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('area_district', models.CharField(blank=True, max_length=20, null=True)),
                ('area_station', models.CharField(blank=True, max_length=50, null=True)),
                ('area_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('area_category', models.CharField(choices=[('dhaka_city', 'dhaka_city'), ('sub-city', 'sub_city'), ('outside_dhaka', 'outside_dhaka')], default='sub-city', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_weight_based', models.BooleanField(blank=True, default=False, null=True)),
                ('dhaka_city_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sub_city_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('out_of_dhaka_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('service_parcel', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_area', models.ManyToManyField(related_name='service_area', to='logistics.area')),
                ('service_merchant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_merchant', to='accounts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='WeightBased',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dhaka_city_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sub_city_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('out_of_dhaka_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='logistics.service')),
            ],
        ),
    ]
