# Generated by Django 5.2.6 on 2025-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area_post_code',
        ),
        migrations.AddField(
            model_name='area',
            name='area_district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='area_station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='service',
            field=models.ManyToManyField(related_name='areas', to='logistics.service'),
        ),
    ]
