# Generated by Django 5.2.6 on 2025-09-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_service_calculated_cod_amount_service_customer_and_more'),
        ('parcels', '0005_parcel_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cod_option',
            field=models.CharField(choices=[('no', 'No COD'), ('yes', 'COD')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='parcel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceparcel', to='parcels.parcel'),
        ),
    ]
