# Generated by Django 5.2.6 on 2025-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_area_area_post_code_area_area_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_category',
            field=models.CharField(choices=[('dhaka_city', 'dhaka_city'), ('sub-city', 'sub_city'), ('outside_dhaka', 'outside_dhaka')], default='sub-city', max_length=50),
        ),
    ]
