# Generated by Django 5.2.6 on 2025-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_service_cod_option_service_parcel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightbased',
            name='cod_option',
            field=models.CharField(choices=[('no', 'No COD'), ('yes', 'COD')], default='no', max_length=10),
        ),
    ]
