# Generated by Django 5.2.6 on 2025-09-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_area_area_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='service',
        ),
    ]
