# Generated by Django 5.2.6 on 2025-09-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_weightbased_cod_option'),
        ('parcels', '0006_parcel_parcels_weightbased_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightbased',
            name='parcel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wbparcel', to='parcels.parcel'),
        ),
    ]
