# Generated by Django 5.2.6 on 2025-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_area_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_area',
            field=models.ManyToManyField(related_name='service', to='logistics.area'),
        ),
    ]
