# Generated by Django 5.2.6 on 2025-09-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_weightbased_parcel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='parcel_id',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='parcel_id',
        ),
    ]
