# Generated by Django 5.2.6 on 2025-09-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.CharField(max_length=50)),
                ('transaction_created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_marchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.merchant')),
                ('transaction_parcel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_amount', models.DurationField(max_length=10)),
                ('invoice_status', models.CharField(max_length=50)),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.transaction')),
            ],
        ),
    ]
