# Generated by Django 5.2.6 on 2025-09-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_soldierearnings'),
        ('billing', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cod', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Bank', 'Bank')], max_length=50)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.deliverysoldier')),
            ],
        ),
    ]
