# Generated by Django 5.2.6 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_soldierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Bank', 'Bank')], max_length=50),
        ),
    ]
