# Generated by Django 5.2.6 on 2025-09-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statement_created_at', models.DateTimeField(auto_now_add=True)),
                ('statement_updated_at', models.DateTimeField(auto_now=True)),
                ('statement_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='billing.transaction')),
            ],
        ),
    ]
