# Generated by Django 5.2.6 on 2025-09-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('parcels_id', models.AutoField(primary_key=True, serialize=False)),
                ('parcels_customer_name', models.CharField(max_length=100)),
                ('parcels_customer_phone', models.CharField(max_length=20)),
                ('parcels_customer_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('parcels_customer_address', models.TextField()),
                ('parcels_cash_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcels_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parcels_item_desc', models.CharField(max_length=255)),
                ('parcels_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_soldier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='accounts.deliverysoldier')),
                ('parcels_area_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='logistics.area')),
                ('parcels_merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='accounts.merchant')),
                ('parcels_service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='logistics.service')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=100)),
                ('action_parcel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel_Timeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeline_note', models.TextField(blank=True, null=True)),
                ('timeline_created_at', models.DateTimeField(auto_now_add=True)),
                ('timeline_updated_at', models.DateTimeField(auto_now=True)),
                ('timeline_action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='parcels.action')),
                ('timeline_parcel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='parcels.parcel')),
            ],
        ),
    ]
