# Generated by Django 5.2.6 on 2025-09-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('logistics', '0002_service_calculated_cod_amount_service_customer_and_more'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_area',
            field=models.CharField(choices=[('dhaka', 'Dhaka City'), ('sub_city', 'Sub City'), ('out_dhaka', 'Out of Dhaka')], default='dhaka', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcels_type',
            field=models.CharField(blank=True, choices=[('documents', 'documents'), ('electronics', 'electronics'), ('clothing', 'clothing'), ('food items', 'food items'), ('other', 'other')], default='other', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Bank', 'Bank')], default='Bkash', max_length=200),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcels_merchant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='accounts.merchant'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcels_service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='logistics.service'),
            preserve_default=False,
        ),
    ]
