# Generated by Django 5.2.6 on 2025-09-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deliverysoldier_soldiers_vehicle'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='assigned_soldier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='accounts.deliverysoldier'),
        ),
    ]
