# Generated by Django 5.2.6 on 2025-09-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_service_calculated_cod_amount_service_customer_and_more'),
        ('parcels', '0002_parcel_delivery_area_parcel_parcels_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcels_service_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='logistics.service'),
        ),
    ]
