# Generated by Django 5.2.6 on 2025-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_alter_parcel_parcels_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='selected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
