# Generated by Django 5.2.6 on 2025-09-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_selected_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
