# Generated by Django 5.2.6 on 2025-09-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_weightbased_cod_option'),
        ('parcels', '0005_parcel_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcels_weightbased_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='logistics.weightbased'),
        ),
    ]
