# Generated by Django 5.2.6 on 2025-09-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_service_parcel_id_and_more'),
        ('parcels', '0006_parcel_parcels_weightbased_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='parcels_weightbased_id',
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcels_weight_based_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_parcels', to='logistics.weightbased'),
        ),
    ]
