# Generated by Django 5.2.6 on 2025-09-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_remove_parcel_parcels_weightbased_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='parcels_type',
        ),
    ]
