# Generated by Django 5.2.6 on 2025-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_remove_parcel_parcels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Bank', 'Bank')], default='Bkash', max_length=200, null=True),
        ),
    ]
