# Generated by Django 5.2.6 on 2025-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_alter_parcel_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcel_status',
            field=models.CharField(choices=[('pending', 'pending'), ('pickup_assigned', 'pickup_assigned'), ('in_transit', 'in_transit'), ('out_of_delivery', 'out_of_delivery'), ('delivered', 'delivered'), ('returned', 'returned')], default='pending', max_length=100),
        ),
    ]
