# Generated by Django 5.2.6 on 2025-09-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0010_parcel_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcels_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
