# Generated by Django 5.2.6 on 2025-09-12 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_address', models.TextField()),
                ('customer_cod_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_parcel_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySoldier',
            fields=[
                ('soldiers_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='soldier/default.png', null=True, upload_to='soldier/')),
                ('soldiers_name', models.CharField(max_length=100)),
                ('soldiers_phone', models.CharField(max_length=20)),
                ('soldiers_nid', models.IntegerField(unique=True)),
                ('soldiers_email', models.EmailField(max_length=254, unique=True)),
                ('soldiers_username', models.CharField(max_length=50, unique=True)),
                ('soldiers_address', models.TextField()),
                ('soldiers_password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('off_duty', 'off_duty'), ('suspended', 'suspended')], default='active', max_length=20)),
                ('soldiers_Blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('soldiers_dob', models.DateField(default=datetime.date.today)),
                ('soldiers_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soldiers_vehicle_type', models.CharField(choices=[('motorcycle', 'motorcycle'), ('scooter', 'scooter'), ('bicycle', 'bicycle'), ('car', 'car')], default='motorcycle', max_length=50)),
                ('soldiers_vehicle_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('soldiers_vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('insurance_status', models.BooleanField(blank=True, default=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_email', models.EmailField(max_length=254, unique=True)),
                ('merchant_phone', models.CharField(max_length=20)),
                ('merchant_business_name', models.CharField(max_length=150)),
                ('merchant_business_number', models.CharField(max_length=50)),
                ('merchant_business_url', models.URLField(blank=True, null=True)),
                ('merchant_pickup_address', models.TextField()),
                ('merchant_username', models.CharField(max_length=50, unique=True)),
                ('merchant_password', models.CharField(max_length=255)),
                ('merchant_category', models.CharField(max_length=100)),
                ('merchant_business_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
