# Generated by Django 5.2.6 on 2025-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_address', models.TextField()),
                ('customer_cod_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_parcel_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySoldier',
            fields=[
                ('soldiers_id', models.AutoField(primary_key=True, serialize=False)),
                ('soldiers_name', models.CharField(max_length=100)),
                ('soldiers_phone', models.CharField(max_length=20)),
                ('soldiers_nid', models.FileField(upload_to='')),
                ('soldiers_email', models.EmailField(max_length=254, unique=True)),
                ('soldiers_username', models.CharField(max_length=50, unique=True)),
                ('soldiers_password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_email', models.EmailField(max_length=254, unique=True)),
                ('merchant_phone', models.CharField(max_length=20)),
                ('merchant_business_name', models.CharField(max_length=150)),
                ('merchant_business_number', models.CharField(max_length=50)),
                ('merchant_business_url', models.URLField(blank=True, null=True)),
                ('merchant_pickup_address', models.TextField()),
                ('merchant_username', models.CharField(max_length=50, unique=True)),
                ('merchant_password', models.CharField(max_length=255)),
                ('merchant_category', models.CharField(max_length=100)),
            ],
        ),
    ]
