# Generated by Django 5.2.6 on 2025-09-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('logistics', '0001_initial'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.area'),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_parcel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel'),
        ),
    ]
