# Generated by Django 5.2.6 on 2025-09-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cod', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='accounts.deliverysoldier')),
            ],
        ),
    ]
