# Generated by Django 5.2.6 on 2025-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merchant_created_at_merchant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
