# Generated by Django 5.2.6 on 2025-09-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merchant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='is_active',
        ),
    ]
