# Generated by Django 5.2.6 on 2025-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_merchant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_business_description',
            field=models.TextField(blank=True),
        ),
    ]
