# Generated by Django 5.2.6 on 2025-09-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merchant_merchant_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='photo',
            field=models.ImageField(blank=True, default='soldier/default.png', null=True, upload_to='soldier/'),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_Blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('off_duty', 'off_duty'), ('suspended', 'suspended')], default='active', max_length=20),
        ),
    ]
