# Generated by Django 5.2.6 on 2025-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deliverysoldier_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_vehicle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
