# Generated by Django 5.2.6 on 2025-09-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deliverysoldier_soldiers_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysoldier',
            name='soldiers_parcel_id',
        ),
    ]
