# Generated by Django 5.2.6 on 2025-09-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_deliverysoldier_soldiers_parcel_id'),
        ('parcels', '0002_parcel_assigned_soldier'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_parcel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel'),
            preserve_default=False,
        ),
    ]
