# Generated by Django 5.2.6 on 2025-09-08 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_deliverysoldier_soldiers_parcel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
