# Generated by Django 5.2.6 on 2025-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_deliverysoldier_soldiers_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysoldier',
            name='soldiers_nid',
            field=models.IntegerField(),
        ),
    ]
