# Generated by Django 5.2.6 on 2025-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_deliverysoldier_soldiers_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
