# Generated by Django 5.2.6 on 2025-09-08 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_deliverysoldier_soldiers_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysoldier',
            name='soldiers_vehicle',
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_vehicle_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='soldiers_vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('bicycle', 'Bicycle'), ('car', 'Car')], default='motorcycle', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
