# Generated by Django 5.2.6 on 2025-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_deliverysoldier_soldiers_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysoldier',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='insurance_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliverysoldier',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
