# Generated by Django 5.2.6 on 2025-09-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_deliverysoldier_insurance_expiry_and_more'),
        ('parcels', '0002_parcel_assigned_soldier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysoldier',
            name='insurance_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverysoldier',
            name='soldiers_nid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='deliverysoldier',
            name='soldiers_parcel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel'),
        ),
        migrations.AlterField(
            model_name='deliverysoldier',
            name='soldiers_vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'motorcycle'), ('scooter', 'scooter'), ('bicycle', 'bicycle'), ('car', 'car')], default='motorcycle', max_length=50),
        ),
    ]
