# Generated by Django 5.2.6 on 2025-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=200)),
                ('notification_content', models.TextField()),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
